services:
#  node_app:
#    develop:
#      watch:
#        - action: sync
#          path: ./dist
#          target: /app
#          ignore:
#            - node_modules/
#        - action: rebuild
#          path: package.json
#    build: .
#    ports:
#      - '9000:9000'
#    environment:
#      NODE_ENV: production
#    volumes:
#      - .:/app
#      - /app/node_modules
#    depends_on:
#      - postgres
#      - redis

  chillz_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/chillz_db
    depends_on:
      - postgres
      - redis
    networks:
      - postgres-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chillz_db
      PGDATA: /var/lib/docker/volumes/pgdata/_data

    networks:
      - postgres-network

    ports:
      - '5432:5432'

  redis:
    image: redis
    ports:
      - '6379:6379'

  redisinsight:
    image: redislabs/redisinsight
    ports:
      - '8001:8001'
    volumes:
      - redisinsight-data:/db
    depends_on:
      - redis


volumes:
  redisinsight-data:
  pgdata:

networks:
  postgres-network:
    driver: bridge
